functions-fetch_view: refactored fetch/view functions

diff --git a/rc_scripts/bashrc.d/functions-fetch_view b/rc_scripts/bashrc.d/functions-fetch_view
--- a/rc_scripts/bashrc.d/functions-fetch_view
+++ b/rc_scripts/bashrc.d/functions-fetch_view
@@ -1,130 +1,145 @@
 #!/bin/bash
 
 # shell functions to download and view in various programs
-_download_viewer () {
-    local OUTPUT_TYPE="$1"
-    local WGET_URL="$2"
-    JSON_XS_CMD=$(which json_xs)
-    VIM_CMD=$(which vim)
-    WGET_CMD=$(which wget)
-    if [ ! -x $JSON_XS_CMD -o ! -x $VIM_CMD -o ! $WGET_CMD ]; then
-        echo "ERROR: missing commands needed to run this function!"
-        echo "JSON_XS_CMD: ${JSON_XS_CMD}"
-        echo "VIM_CMD: ${VIM_CMD}"
-        echo "WGET_CMD: ${WGET_CMD}"
-        return 1
-    fi
-    if [ "x$1" == "x" ]; then
-        echo "Usage: view${OUTPUT_TYPE} \"http://example.com/api/request.json\""
-        echo "(Hint: quote URL to prevent shell from interpreting URL)"
-        return 1
-    else
-        $WGET_CMD -O - "$WGET_URL" | $JSON_XS_CMD \
-            | $VIM_CMD --cmd 'let no_plugin_maps = 1' \
-            -c 'runtime! macros/less.vim' -c "set filetype=$OUTPUT_TYPE" -
-    fi
-    unset JSON_XS_CMD VIM_CMD WGET_CMD
-} # view a downloaded file, pretty printed and syntax highlighted
 
-viewjson () {
-    _download_viewer "json" "$1"
-} # json front end to _download_viewer
-
-viewyaml () {
-    _download_viewer "yaml" "$1"
-} # yaml front end to _download_viewer
-
-xxdfetch () {
-    local WGET_URL=$1
-    local XXD_CMD=$(which xxd)
+# view a downloaded/local file, pretty printed and syntax highlighted
+_fetchview () {
+    local FETCH_CMD="$1"
+    local VIEW_CMD="$2"
+    local TYPE="$3"
+    local URL="$4"
+    local FULL_VIEW_CMD=$(which ${VIEW_CMD})
     local VIM_CMD=$(which vim)
-    local WGET_CMD=$(which wget)
-    if [ ! -x $XXD_CMD -o ! -x $VIM_CMD -o ! $WGET_CMD ]; then
-        echo "ERROR: missing commands needed to run this function!"
-        echo "XXD_CMD: ${XXD_CMD}"
-        echo "VIM_CMD: ${VIM_CMD}"
-        echo "WGET_CMD: ${WGET_CMD}"
-        return 1
-    fi
-    if [ "x${WGET_URL}" == "x" ]; then
-        echo "Usage: xxdfetch \"http://example.com/api/request.json\""
-        echo "(Hint: quote URL to prevent shell from interpreting URL)"
-        return 1
-    else
-        $WGET_CMD -O - "${WGET_URL}" | $XXD_CMD \
-            | $VIM_CMD --cmd 'let no_plugin_maps = 1' \
-            -c 'runtime! macros/less.vim' -c "set filetype=xxd" -
-    fi
-} # xxd downloader and viewer
 
-xxdless () {
-    local LESS_FILE=$1
-    if [ "x$LESS_FILE" = "x" ]; then
-        echo "Usage: xxdless <filename>"
-        return 1
+    if [ $FETCH_CMD = "wget" ]; then
+        local WGET_CMD=$(which wget)
+        local FULL_FETCH_CMD="${WGET_CMD} -O -"
+    elif [ $VIEW_CMD = "cat" ]; then
+        local FULL_FETCH_CMD="cat"
+    else
+        echo "ERROR: unknown fetch command '${FETCH_CMD}'"
+        exit 1
     fi
-    local XXD_CMD=$(which xxd)
-    local VIM_CMD=$(which vim)
-    if [ ! -x $XXD_CMD -o ! -x $VIM_CMD ]; then
-        echo "ERROR: missing commands needed to run this function!"
-        echo "XXD_CMD: ${XXD_CMD}"
-        echo "VIM_CMD: ${VIM_CMD}"
-        return 1
-    fi
-    $XXD_CMD $LESS_FILE \
+
+    $FULL_FETCH_CMD "$URL" | $FULL_VIEW_CMD \
         | $VIM_CMD --cmd 'let no_plugin_maps = 1' \
-        -c 'runtime! macros/less.vim' -c "set filetype=xxd" -
-} # xxd "less" command
+        -c 'runtime! macros/less.vim' -c "set filetype=${TYPE}" -
+}
 
+# check that all of the commands required to view a file are present on the
+# system
+_fetchview_check_cmds () {
+    local CHECK_CMDS="$@"
+    local CHECK_ERROR=0
+
+    for CHECK_CMD in $CHECK_CMDS;
+    do
+        local WHICH_CMD=$(which ${CHECK_CMD})
+        if [ ! -x $WHICH_CMD ]; then
+            echo "ERROR: ${CHECK_CMD_NAME} missing/not executable"
+            CHECK_ERROR=$(($CHECK_ERROR + 1))
+        fi
+    done
+    if [ $CHECK_ERROR -gt 0 ]; then
+        exit 1
+    fi
+}
+
+# check to see that a URL was passed in
+_fetchview_url_check () {
+    local URL=$1
+    local TYPE=$2
+    if [ "x$URL" == "x" ]; then
+        echo "ERROR: Missing file URL"
+        echo "Usage: fetch${TYPE} \"http://example.com/api/request.${TYPE}\""
+        echo "(Hint: quote URL to prevent shell from interpreting URL)"
+        exit 1
+    fi
+}
+
+# check to see that a filename was passed in
+_fetchview_file_check () {
+    local URL=$1
+    local TYPE=$2
+    if [ ! -e "$URL" ]; then
+        echo "ERROR: Missing file ${URL} on the local filesystem"
+        echo "Usage: less${TYPE} /path/to/file.${TYPE}"
+        exit 1
+    fi
+}
+
+# fetch and view a JSON file from the intarwebs
+fetchjson () {
+    local URL="$1"
+    _fetchview_url_check "$URL" "json"
+    _fetchview_check_cmds "vim" "wget" "json_xs"
+    # $1 = fetch command, $2 = view command, $3 = file type, $4 = URL
+    _fetchview "wget" "json_xs" "json" "$URL"
+}
+
+# fetch and view a YAML file from the intarwebs
+fetchyaml () {
+    local URL="$1"
+    _fetchview_url_check "$URL" "yaml"
+    _fetchview_check_cmds "vim" "wget" "json_xs"
+    # $1 = fetch command, $2 = view command, $3 = file type, $4 = URL
+    _fetchview "wget" "json_xs" "yaml" "$URL"
+}
+
+# fetch and view an XML file from the intarwebs
+fetchxml () {
+    local URL="$1"
+    _fetchview_url_check "$URL" "xml"
+    _fetchview_check_cmds "vim" "wget" "xml_pp"
+    # $1 = fetch command, $2 = view command, $3 = file type, $4 = URL
+    _fetchview "wget" "xml_pp" "xml" "$URL"
+}
+
+# fetch a URL, view it in 'xxd'
+fetchxxd () {
+    local URL="$1"
+    _fetchview_url_check "$URL" "xxd"
+    _fetchview_check_cmds "vim" "wget" "xxd"
+    # $1 = fetch command, $2 = view command, $3 = file type, $4 = URL
+    _fetchview "wget" "xxd" "xxd" "$URL"
+}
+
+# view a local JSON file
 lessjson () {
-    local LESS_FILE=$1
-    if [ "x$LESS_FILE" = "x" ]; then
-        echo "Usage: lessjson <filename>"
-        return 1
-    fi
-    JSON_XS_CMD=$(which json_xs)
-    VIM_CMD=$(which vim)
-    if [ ! -x $JSON_XS_CMD -o ! -x $VIM_CMD ]; then
-        echo "ERROR: missing commands needed to run this function!"
-        echo "JSON_XS_CMD: ${JSON_XS_CMD}"
-        echo "VIM_CMD: ${VIM_CMD}"
-    fi
-    if [ -f $LESS_FILE ]; then
-        cat $LESS_FILE | $JSON_XS_CMD \
-            | $VIM_CMD --cmd 'let no_plugin_maps = 1' \
-            -c 'runtime! macros/less.vim' -c "set filetype=json" -
-    else
-        echo "ERROR: file $LESS_FILE not found/readable"
-        return 1
-    fi
+    local URL="$1"
+    _fetchview_file_check "$URL" "json"
+    _fetchview_check_cmds "vim" "cat" "json_xs"
+    # $1 = fetch command, $2 = view command, $3 = file type, $4 = URL
+    _fetchview "cat" "json_xs" "json" "$URL"
 }
 
-lessxml () {
-    local LESS_FILE=$1
-    if [ "x$LESS_FILE" = "x" ]; then
-        echo "Usage: lessxml <filename>"
-        return 1
-    fi
-    #XML_PP_CMD=$(which tidy)
-    XML_PP_CMD=$(which xml_pp)
-    VIM_CMD=$(which vim)
-    if [ ! -x $XML_PP_CMD -o ! -x $VIM_CMD ]; then
-        echo "ERROR: missing commands needed to run this function!"
-        echo "XML_PP_CMD: ${XML_PP_CMD}"
-        echo "VIM_CMD: ${VIM_CMD}"
-    fi
-    if [ -f $LESS_FILE ]; then
-        # for 'tidy'
-        #cat $LESS_FILE | $XML_PP_CMD -xml -quiet \
-        # for 'xml_pp'
-        cat $LESS_FILE | $XML_PP_CMD \
-            | $VIM_CMD --cmd 'let no_plugin_maps = 1' \
-            -c 'runtime! macros/less.vim' -c "set filetype=xml" -
-    else
-        echo "ERROR: file $LESS_FILE not found/readable"
-        return 1
-    fi
+# view a local YAML file
+lessyaml () {
+    local URL="$1"
+    _fetchview_file_check "$URL" "yaml"
+    _fetchview_check_cmds "vim" "wget" "json_xs"
+    # $1 = fetch command, $2 = view command, $3 = file type, $4 = URL
+    _fetchview "wget" "json_xs" "yaml" "$URL"
 }
+
+# view a local XML file
+lessxml () {
+    local URL="$1"
+    _fetchview_file_check "$URL" "xml"
+    _fetchview_check_cmds "vim" "cat" "xml_pp"
+    # $1 = fetch command, $2 = view command, $3 = file type, $4 = URL
+    _fetchview "cat" "xml_pp" "xml" "$URL"
+}
+
+# fetch a local file, view it in 'xxd'
+lessxxd () {
+    local URL="$1"
+    _fetchview_file_check "$URL" "xxd"
+    _fetchview_check_cmds "vim" "cat" "xxd"
+    # $1 = fetch command, $2 = view command, $3 = file type, $4 = URL
+    _fetchview "cat" "xxd" "xxd" "$URL"
+}
+
 
 # vi: set filetype=sh shiftwidth=4 tabstop=4
 # конец!
